berlindb/core

- query.php
This also makes Compare queries work correctly, again.
Fixes #8.
> Issue/8 - Use 'compare_query' over 'compare'.

- query.php
This commit fixes a bug that was preventing single item caches from being cleaned when an item was deleted.
Props felipeelia.
Fixes #27.
> Issue/27 - Query: in clean_item_cache(), make an array instead of cast to array.

- query.php
This change resolves this problem because `delete_metadata_by_mid` uses `_get_meta_table` to retrieve the meta table from the database. This function automatically appends `meta` to the table name, and does not need a prefix.
Due to this, there is no need to do anything but directly pass `table_name` to `delete_metadata_by_mid`.
Resolves #51
> Updates delete_metadata_by_mid to use table name, not the parsed meta table name. #51

- table.php
We could potentially use a foreach loop here, but I figured I'd keep the code as similar as it was as possible. Basically, I just changed the filter to use the key of `$versions`, which is the version number. Prior to this, it un-intentionally used the values of `$versions`, which is supposed to be the callback.
> Updates upgrade filter to use the upgrade version instead of the callback

- query.php
First pass at allowing querying explicitly for falsy values `(0, '0', false, null)`
This work-in-progress is a proof-of-concept at how we could potentially avoid bugs with `empty()` checks against `query_vars`.
See #21.
> Issue/21 - Introduce query_var_default_value and is_query_var_default().

- date.php
- query.php
This commit updates the Query and Queries\Date classes to bring it more closely inline with Meta & Compare.
Queries\Date specifically recieves:
* Adds get_column() and get_relation() to match get_compare()
* Uses get_ methods in __construct() and sanitize_query()
* Updates get_sql() to return both join & where clauses
* Defines all in_array() haystacks
* Strict in_array() usages
* Updates column handling
* Improves docs
* Empty/Isset audit & minor changes
Fixes #36.
> Issue/36 - Refactor Queries\Date to better match Meta & Compare.

- table.php
This commit wraps the SQL necessary to clone a table and copy its contents into 2 separate helper methods.
Fixes #38.
> Issue/38 - Table: add clone() and copy() methods.

- column.php
- date.php
Berlin enforces storing datetime values according to UTC/GMT. For WordPress, date/gmdate are essentially synonymous, making these functions easy to conflate.
A future version of validate_datetime() may implement its own time zone handler, as a way to internally override/verify the UTC result, but gmdate() here is a small step towards that.
Fixes #75.
> Column: In validate_datetime(), prefer gmdate() over date().

- column.php
- query.php
Up until now, the "Column::allow_null" flag was only partially implemented, working sometimes for "datetime" columns, but not for any others.
This commit ensures that, in the "Query::validate_item" method, null values for all item keys are allowed when "allow_null" is true for that column, and returns false early when attempting to save a null value to an item key when it is not allowed.
This commit also removes the special datetime, column type, null value handling that was added as part of #22, since it is now explicitly globally allowed (when allowed) in the global validator.
This commit also modifies "Column::sanitize_default" to only allow null defaults when "allow_null" is true, adds explicit support for strings and integers, and adds a @todo regarding other column types that may …
> Issue/76-jjj - Nulls: validate null values if allowed, on any column.

- date.php
This commit deepens the assumption and requirement that `UTC` is the expected system time zone.
Fixes #82.
> Issue/82 - Prefer `gmmktime()` over `mktime()`.

- date.php
This commit is necessary to remove dependency on `get_option( 'start_of_week' )` WordPress setting.
This commit includes some code formatting changes to align surrounding lines as needed.
Fixes #80
> Add support for 'start_of_week' first-order clause.

- query.php
This change fixes delete_all_item_meta() and allows proper deletion of meta data when a Row is deleted via a Query.
It acheives this by using the correct meta-type string for the given meta data action taking place, thanks to the way that _get_meta_table() works internally.
Fixes #84
> Issue/84 - Query: introduce get_meta_type() and improve get_meta_table_name()

- query.php
This change introduces a way to allow for copying an existing item/Row in the database, with the option to override that data via the $data parameter.
The goal of including this method as a low-level API is to reduce the amount of code necessary to support this action higher up in the application layer (global functions, etc...)
Fixes #88
> Query: add copy_item() method.

- table.php
This change prevents quotes around the $column value by not preparing it, and also by making sure its value is only 1 of 2 intended columns: Key_name and Column_name.
This fixes incorrectly generated SQL, allowing this method to function as intended instead of incorrectly returning no results.
Props @ashleyfae. Fixes #87.
> Table: fix format of query inside index_exists().

- query.php
> Query: replace hardcoded 'id' references with primary column name.

- query.php
This change removes the forced stripping of slashes on string content columns before saving them to the database.
Based on developer feedback, the consensus is that this decision belongs higher up in the application stack, and not in a low-level database API.
Fixes #97.
> Issue/97 - Query: remove stripslashes() in ::validate_item()

- query.php
This change ensures that, by default, parsing the groupby clause of a query will match the behavior of parsing fields.
See #106.
> Issue/106 - Query: pass $alias from parse_fields() into parse_groupby() call.

- table.php
This change ensures that the Table version info (currently saved in wp_options) is always deleted if drop() fails because the tables already do not exist.
Fixes #108. Props @Mai-Saad.
> Issue/108 - Table: when uninstalling, delete version info if not exists.

- src/Database/Query.php
This commit adds a third parameter to transition_item() for the item ID to be passed directly into it rather than derived from the old data.
Previously, it was possible that the old data would be of a mixed type, potentially an integer in the case of a newly added item. This was weird and confusing. Now old data will just be an empty array (because there is no old data) and the third parameter will include the item ID which is known from the previous MySQL query result.
Additionally, this commit updates a bunch of inline docs relative to when shape_item_id() is called to make everything consistent where it makes sense.
Fixes #113.
> Issue/113 - Query: audit shape_item_id() usages.

- src/Database/Table.php
For PHP 5.6 compatibility.
Fixes #38.
> Table: add _clone() shim from Sugar Calendar.

- src/Database/Query.php
Fixes #132
Proposed Changes:
1. Registers a new dynamic hook (eg `edd_order_deleted`) when an item is deleted. The two parameters are the original item ID and the result of the delete action.
> Create dynamic hook after an item is deleted

- src/Database/Table.php
Fixes #156
Proposed Changes:
Sets the default value for getting the table version from the database to `1`, an arbitrary and low number. This won't affect creating new tables, but if a table exists and does not have a version number, it will allow upgrades to be collected and run.
> Set db version default to 1

- src/Database/Base.php
Fixing an incorrect attribute in previous [PR](https://github.com/berlindb/core/pull/155)
Updated to use correct attribute to allow dynamic properties as seen [here](https://www.php.net/manual/en/class.allowdynamicproperties.php)
> Updated to use correct attribute to allow dyanmic properties

- src/Database/Query.php
Fixes #162 
I added a new property `$current_item_shape` which is setted at each request to prevent a shape to be reused in another one later.
> Added $current_item_shape to prevent impacting a query with another.

- src/Database/Table.php
This PR attempts to fix this issue #165 
The current usage of `SHOW TABLES LIKE` work fine but for large db it have a negative effect on performance, changing that to `SELECT..` statements is more efficient and improve performance.
> Modified the query statement to check information schema

- src/Database/Queries/Date.php
This PR attempts to fix the issue described in #9699 
Use the received table name & table alias arguments in the `get_sql` function to set those as properties on the Date class. Note that `get_sql` already gets called with those params as per the line below. However the `get_sql` function oddly wasn't defining those arguments in its definition.
https://github.com/awesomemotive/easy-digital-downloads/blob/715373d18971c8b12e949bb3fd5d6c40aac6c234/includes/database/engine/class-query.php#L1363 
Then, when building the SQL query, use the alias or name (only if available) to prepend to the column name in the query. This prevents ambiguity issues when performing the SQL query
This prevents and fixes the issue described in https://github.com/awesomemotive/easy-digital-downloads/issues/9699
I am …
> Use table alias/name when building date query
