- README.md
> My name is BerlinDB

- query.php
> Prepare basic WHERE clause in Query::get_results() #33

- query.php
Also, only strip slashes from string item values.
Fixes #22.
> Issue/22 - Allow null values to be saved to item columns that allow them.

- query.php
> Correct column validation in Query::get_results() to check array key #31

- query.php
> Unset where columns using the index to fix #41

- compare.php
- meta.php
- query.php
> Issue/44 - Abstract WP_Meta_Query dependency into custom Meta class

- date.php
> Corrects base namespace in extends declaration. #15

- table.php
> Issue/37 - Table: Add `index_exists()` method.

- query.php
This PR adds a tweak to the documentation for the query constructor. It clarifies how date queries can be used.
Issue #67
> Issue/67 - Improve Query constructor documentation

- column.php
- query.php
> Issue/71 - Improvements to get_item() & friends

- base.php
- column.php
- query.php
- table.php
See: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8136/files/f228a91601dd976b9cf56d99e885aa3bfa9673b4
> Issue/73 - Various updates from EDD3 suggestions.

- query.php
> Issue/98 - Query: only update relevant columns in update_item()

- src/Database/Query.php
Closes #101
@JJJ I branched this from `release/2.0.0` - let me know if you want me to change it.
> Check if 'where' is empty before using #101

- table.php
This change improves compatibility with temporary tables used in PHPUnit test suites.
Fixes #104.
> Issue/104 - Table: update approach inside exists().

- table.php
This change adds the ability to query a database table and get its columns as standard objects.
Fixes #111.
> Issue/111 - Table: add columns() method.

- src/Database/Base.php
- src/Database/Column.php
- src/Database/Queries/Date.php
- src/Database/Query.php
- src/Database/Row.php
- src/Database/Table.php
> PR/115 - Recommendations from phpstan.

- src/Database/Base.php
> Make booleans much better

- src/Database/Query.php
Looks like a search & replace might have caused it
> Fix comment description for $order param

- src/Database/Base.php
- src/Database/Query.php
> WIP - Issue/128

- src/Database/Base.php
- src/Database/Column.php
- src/Database/Queries/Date.php
- src/Database/Query.php
- src/Database/Schema.php
> Resolve PHPStan Level 0 errors

- src/Database/Table.php
`$global` is already a boolean
> Fix boolean handling in Table

- src/Database/Base.php
Allow dynamic properties on Base class.
> Added attribute to allow dynamic properties

- src/Database/Query.php
This PR corrects the return type of `Query::add_item()` and `Query::copy_item()`.
> Fix the return type of Query::add_item()
